version: "3.8"

services:
  nextjs:
    image: node:18-alpine
    container_name: nextjs-app
    working_dir: /usr/src/app
    volumes:
      - ./nextjs-app:/usr/src/app
    expose:
      - "3000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
